name: SQL Deployment

on: [push, workflow_dispatch]

jobs:
  
  deploy:
    name: Build and deploy sql project
    runs-on: ubuntu-20.04
    environment: Production
    strategy:
      matrix:
        dotnet-version: [5.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
